swagger: "2.0"
info:
  title: WantGo API
  description: This is WantGoAPI
  version: ""
host: localhost:8081
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /card-list:
    get:
      tags:
      - WantGo
      summary: getSimpleCardList WantGo
      operationId: WantGo#getSimpleCardList
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/simpleCardResponse'
      schemes:
      - http
  /card/{cardId}:
    get:
      tags:
      - WantGo
      summary: getCardInfo WantGo
      operationId: WantGo#getCardInfo
      parameters:
      - name: cardId
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/WantGoGetCardInfoResponseBody'
      schemes:
      - http
    put:
      tags:
      - WantGo
      summary: putCardInfo WantGo
      operationId: WantGo#putCardInfo
      parameters:
      - name: cardId
        in: path
        description: card id
        required: true
        type: integer
      - name: string
        in: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK response.
      schemes:
      - http
    post:
      tags:
      - WantGo
      summary: postCardInfo WantGo
      operationId: WantGo#postCardInfo
      parameters:
      - name: cardId
        in: path
        description: card id
        required: true
        type: integer
      - name: string
        in: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK response.
      schemes:
      - http
    delete:
      tags:
      - WantGo
      summary: deleteCardInfo WantGo
      operationId: WantGo#deleteCardInfo
      parameters:
      - name: cardId
        in: path
        description: card id
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - WantGo
      summary: Download ./gen/http/openapi.json
      operationId: WantGo#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  WantGoGetCardInfoResponseBody:
    title: WantGoGetCardInfoResponseBody
    type: object
    properties:
      cardAuthor:
        type: string
        default: default
        example: Odio officia aut cupiditate asperiores qui id.
      cardDescription:
        type: string
        default: default
        example: Ratione non voluptatem molestiae.
      cardTitle:
        type: string
        default: default
        example: Consequatur id.
      imageUrl:
        type: string
        default: default
        example: Est dolore.
      locationAddress:
        type: string
        default: default
        example: Error quia odit.
      locationUrl:
        type: string
        default: default
        example: Veniam aut sunt voluptatibus.
      tags:
        type: array
        items:
          type: string
          example: Et quisquam autem reiciendis at numquam.
        example:
        - Corporis eaque.
        - Vero libero qui dolorem.
        - Earum quis dolorem quo eos adipisci unde.
        - Unde corrupti ipsum aut.
    example:
      cardAuthor: Odit et placeat debitis consectetur.
      cardDescription: Voluptatum voluptas qui quod aut.
      cardTitle: Nesciunt ut aliquid.
      imageUrl: Maxime est dicta.
      locationAddress: Delectus sapiente maiores culpa et.
      locationUrl: Qui dolores animi dolore et.
      tags:
      - Accusamus quam vitae magni asperiores ipsum accusantium.
      - Officiis ut.
  simpleCardResponse:
    title: simpleCardResponse
    type: object
    properties:
      cardAuthor:
        type: string
        default: default
        example: Ad aut dolorum deleniti id et.
      cardId:
        type: integer
        default: 0
        example: 6598837571395036910
        format: int64
      cardTitle:
        type: string
        default: default
        example: Ut labore vel nihil est.
      imageUrl:
        type: string
        default: default
        example: Rerum dignissimos.
    example:
      cardAuthor: Esse non rem asperiores dolore omnis voluptas.
      cardId: 324493412898009656
      cardTitle: Sequi est.
      imageUrl: Hic et aperiam temporibus eum qui.
